name: tests

on: [push, pull_request]

jobs:

  ubuntu:
    name: Swift ${{ matrix.swift }} on ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        swift: ["5.0", "5.1", "5.2", "5.3", "5.4", "5.5", "5.6", "latest"]
    container: swift:${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift ${{ matrix.swift }}
        uses: swift-actions/setup-swift@v1.15.0
        with:
          swift-version: ${{ matrix.swift }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test --enable-test-discovery -v
        
  macOS:
    name: Swift ${{ matrix.swift }} on macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        swift: ["5.0", "5.1", "5.2", "5.3", "5.4", "5.5", "5.6"]
    container: swift:${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift ${{ matrix.swift }}
        uses: swift-actions/setup-swift@v1.15.0
        with:
          swift-version: ${{ matrix.swift }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
