name: tests

on: [pull_request]

jobs:

  generate-linuxmain:
    name: Generating Linuxmain.swift for Linux testing
    runs-on: ["macos-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generating Linuxmain.swift
        run: swift test --generate-linuxmain -v

  ubuntu:
    name: Swift ${{ matrix.swift }} on ubuntu-latest
    needs: generate-linuxmain
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        swift: ["5.0", "5.1", "5.2", "5.3", "5.4", "5.5", "5.6", "latest"]
    container:
      image: swift:${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build --enable-test-discovery -v
      - name: Run tests
        run: swift test --enable-test-discovery -v
        
  macos:
    name: Swift ${{ matrix.swift }} on macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        swift: ["5.0", "5.1", "5.2", "5.3", "5.4", "5.5", "5.6"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
        
