name: tests

on: [pull_request]

jobs:
  ubuntu:
    name: Swift ${{ matrix.swift }} on ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        swift: ["5.1", "5.2", "5.3", "5.4", "5.5", "5.6", "5.7", "5.8", "latest"]
    container:
      image: swift:${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build -v --enable-test-discovery
      - name: Run tests
        run: swift test -v --enable-test-discovery
        
  macos:
    name: Default Swift version on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-10.15", "macos-11", "macos-12", "macos-13", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
        
